DX-914: Add build_gem.sh and generate version number in variaables.sh

diff --git a/.github/workflows/gem.yml b/.github/workflows/gem.yml
--- a/.github/workflows/gem.yml
+++ b/.github/workflows/gem.yml
@@ -1,76 +1,65 @@
 name: Ruby Gem
 
-on:
-  push:
-    branches:
-    - '*'
-    tags:
-    - '*'
-  pull_request:
+on: [push, pull_request]
 
 jobs:
-  build:
+  variables:
     runs-on: ubuntu-latest
+    outputs:
+      branch: ${{ steps.variables.outputs.branch }}
+      version: ${{ steps.variables.outputs.version }}
+      repository_url: ${{ steps.variables.outputs.repository_url }}
+
+    steps:
+      - uses: actions/checkout@v2
+        with:
+          fetch-depth: 0
+
+      - uses: gittools/actions/gitversion/setup@v0.9.10
+        with:
+          versionSpec: '5.x.x'
+
+      - id: gitversion
+        uses: gittools/actions/gitversion/execute@v0.9.10
+
+      - name: Generate variables
+        id: variables
+        env:
+          GITHUB_CONTEXT: ${{ toJson(github) }}
+        run: .github/scripts/variables.sh ${{ steps.gitversion.outputs.legacySemVerPadded }}
+
+  gem:
+    needs: variables
+    runs-on: ubuntu-latest
+    outputs:
+      name: ${{ steps.gem.outputs.name }}
 
     steps:
     - uses: actions/checkout@v2
-      with:
-        fetch-depth: 0
 
-    - name: Set up Ruby 2.7
-      uses: ruby/setup-ruby@v1
+    - uses: ruby/setup-ruby@v1
       with:
         ruby-version: 2.7
         bundler-cache: true
 
-    - name: Install GitVersion
-      uses: gittools/actions/gitversion/setup@v0.9.10
-      if: startsWith(github.ref, 'refs/tags/') != true # Only use GitVersion for unstable builds
-      with:
-        versionSpec: '5.x.x'
-
-    - name: Execute GitVersion
-      id: gitversion
-      if: startsWith(github.ref, 'refs/tags/') != true
-      uses: gittools/actions/gitversion/execute@v0.9.10
-
-    - name: Create gem version number
-      id: gemversion
-      uses: actions/github-script@v5
-      with:
-        github-token: ${{ secrets.GITHUB_TOKEN }}
-        script: |
-          const gemVersion = (function() {
-            const ref = '${{ github.ref }}';
-            const tagPrefix = 'refs/tags/';
-
-            if (ref.startsWith(tagPrefix)) {
-              // If a tag ref is being built, just return the tag verbatim
-              return ref.substring(tagPrefix.length);
-            }
-
-            return '${{ steps.gitversion.outputs.legacySemVerPadded }}';
-          })();
-
-          core.setOutput('version', gemVersion);
-
-    - name: Version stamp
-      run: sed -i -e 's/0.0.1.dev/${{ steps.gemversion.outputs.version }}/g' ./lib/gem_version.rb
-
     - name: Build gem
       id: gem
-      env:
-        GEM_VERSION: ${{ steps.gemversion.outputs.version }}
-      run: |
-        GEM_BUILD_NAME=$(gem build swedbank-pay-design-guide-jekyll-theme.gemspec | awk '/File/ {print $2}')
-        echo "Gem filename: '${GEM_BUILD_NAME}'"
-        echo "::set-output name=name::${GEM_BUILD_NAME}"
+      run: .github/scripts/build_gem.sh --version "${{ needs.variables.outputs.version }}" --verbose
 
     - name: Upload artifact
       uses: actions/upload-artifact@v2-preview
       with:
         name: ${{ steps.gem.outputs.name }}
         path: ${{ steps.gem.outputs.name }}
+
+  publish:
+    needs: [gem, variables]
+    runs-on: ubuntu-latest
+
+    steps:
+    - uses: actions/download-artifact@v2
+      with:
+        name: ${{ needs.gem.outputs.name }}
 
     - name: Publish to GPR
       env:
@@ -84,8 +73,8 @@ jobs:
         set -e
         gem push --KEY github \
                  --host https://rubygems.pkg.github.com/${OWNER} \
-                 ${{ steps.gem.outputs.name }} \
-          || echo "push failed ($?) probably due to version '${{ steps.gemversion.outputs.version }}' already existing in GPR."
+                 ${{ needs.gem.outputs.name }} \
+          || echo "push failed ($?) probably due to version '${{ needs.variables.outputs.version }}' already existing in GPR."
 
     - name: Publish to RubyGems
       if: startsWith(github.ref, 'refs/tags/') # Only publish tagged commits
@@ -96,4 +85,4 @@ jobs:
         touch $HOME/.gem/credentials
         chmod 0600 $HOME/.gem/credentials
         printf -- "---\n:rubygems_api_key: ${RUBYGEMS_API_KEY}\n" > $HOME/.gem/credentials
-        gem push ${{ steps.gem.outputs.name }}
+        gem push ${{ needs.gem.outputs.name }}
